default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: mbta_development

test:
  <<: *default
  database: mbta_test

production:
  <<: *default
  database: mbta_production
  username: mbta
  password: <%= ENV['MBTA_DATABASE_PASSWORD'] %>
